{
  imports = [
    ./acme.nix
    ./atuin.nix
    ./bitmagnet.nix
    ./collie.nix
    ./derp.nix
    ./immich.nix
    ./kopia.nix
    ./light-server.nix
    ./media.nix
    ./monitoring.nix
    ./mutagen-sync.nix
    ./ncps.nix
    ./new-api.nix
    ./open-webui.nix
    ./openlist.nix
    ./powerdns.nix
    ./py-kms.nix
    ./restic.nix
    ./znapzend.nix
  ];
}
