alias -g stat_='sort | uniq -c | sort -nk 1'
alias codex='nix run --accept-flake-config github:gaoyifan/nix#codex --'
alias cursor-agent='nix run --accept-flake-config github:gaoyifan/nix#cursor-cli --'
alias ls='ls -G --color=auto'
alias ncdu='ncdu -x --exclude "com~apple~CloudDocs" --exclude "Mobile Documents"'
